name: Arma

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build addon with HEMTT
        uses: arma-actions/hemtt@master
        with:
          command: 'build --release'
      - uses: actions/upload-artifact@master
        with:
          name: '@LambsDanger'
          path: 'releases/@LambsDanger*.zip'
